name: Ubuntu-Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Ubuntu script
      run: bash ubuntu-run.sh

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 340
